### ISSUE TITLE
tidyped does not work with trace='all' in certain cases

### ISSUE THREAD

**Issue by larahurban** [luansheng/visPedigree#2]
Thank you very much for this easy-to-use pedigree visualisation tool!

I have just had one issue so far: When I want to visualise a subset of my tree by using the 'cand' option, it works fine if I only give the ID of one individual. When I give a list of individuals, it still works fine as long as the 'trace' option ist set to 'up' or 'down'. But when I use 'all', I get the following error: 
Error in checkped(ped_new, addgen) : Please check the pedigree!

As I did not change the pedigree or candidate list as compared to the 'up'/'down' run, I suspect that this might be a bug in the code. Could you help me with this, please?

**Comment by luansheng** [comment]
OK. I will revise it for 3-5 days.

**Comment by luansheng** [comment]
This bug has been fixed. A new version of 0.2.5 is released.

**Comment by larahurban** [comment]
Thank you very much!

**Comment by larahurban** [comment]
Sorry, one more issue: now it seems that visPedigree is not available anymore for R version 3.5.1; is this expected?

**Comment by luansheng** [comment]
I am not sure what happend. It's OK when I use R 3.6.1.
Sheng luan



---Original---

**Comment by larahurban** [comment]
That is weird, should this update not extend to other versions? Lara

**Comment by luansheng** [comment]
I try to add the depends of R (>=3.5.1). I am not sure it is ok.
Thanks.



luansheng@foxmail.com
 
From: Lara
Date: 2020-03-03 13:41
To: luansheng/visPedigree
CC: Sheng Luan; State change
Subject: Re: [luansheng/visPedigree] tidyped does not work with trace='all' in certain cases (#2)
That is weird, should this update not extend to other versions? Lara

**Comment by larahurban** [comment]
Sorry for the very late reply. Yes, it is working now! Many thanks.
